//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntFrm.DataAdapter.DicContentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:hl7-org:v3", ConfigurationName="DicContentService.IDicContent")]
    public interface IDicContent {
        
        // CODEGEN: 命名空间 urn:hl7-org:v3 的元素名称 serviceID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EntFrm.DataAdapter.DicContentService.getDicContentByPageResponse getDicContentByPage(EntFrm.DataAdapter.DicContentService.getDicContentByPage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EntFrm.DataAdapter.DicContentService.getDicContentByPageResponse> getDicContentByPageAsync(EntFrm.DataAdapter.DicContentService.getDicContentByPage request);
        
        // CODEGEN: 命名空间 urn:hl7-org:v3 的元素名称 serviceID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EntFrm.DataAdapter.DicContentService.getDicContentResponse getDicContent(EntFrm.DataAdapter.DicContentService.getDicContent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EntFrm.DataAdapter.DicContentService.getDicContentResponse> getDicContentAsync(EntFrm.DataAdapter.DicContentService.getDicContent request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDicContentByPage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDicContentByPage", Namespace="urn:hl7-org:v3", Order=0)]
        public EntFrm.DataAdapter.DicContentService.getDicContentByPageBody Body;
        
        public getDicContentByPage() {
        }
        
        public getDicContentByPage(EntFrm.DataAdapter.DicContentService.getDicContentByPageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:hl7-org:v3")]
    public partial class getDicContentByPageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pageNum;
        
        public getDicContentByPageBody() {
        }
        
        public getDicContentByPageBody(string serviceID, string pageNum) {
            this.serviceID = serviceID;
            this.pageNum = pageNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDicContentByPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDicContentByPageResponse", Namespace="urn:hl7-org:v3", Order=0)]
        public EntFrm.DataAdapter.DicContentService.getDicContentByPageResponseBody Body;
        
        public getDicContentByPageResponse() {
        }
        
        public getDicContentByPageResponse(EntFrm.DataAdapter.DicContentService.getDicContentByPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDicContentByPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDicContentByPageResponseBody() {
        }
        
        public getDicContentByPageResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDicContent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDicContent", Namespace="urn:hl7-org:v3", Order=0)]
        public EntFrm.DataAdapter.DicContentService.getDicContentBody Body;
        
        public getDicContent() {
        }
        
        public getDicContent(EntFrm.DataAdapter.DicContentService.getDicContentBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:hl7-org:v3")]
    public partial class getDicContentBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fieldName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fieldValue;
        
        public getDicContentBody() {
        }
        
        public getDicContentBody(string serviceID, string fieldName, string fieldValue) {
            this.serviceID = serviceID;
            this.fieldName = fieldName;
            this.fieldValue = fieldValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDicContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDicContentResponse", Namespace="urn:hl7-org:v3", Order=0)]
        public EntFrm.DataAdapter.DicContentService.getDicContentResponseBody Body;
        
        public getDicContentResponse() {
        }
        
        public getDicContentResponse(EntFrm.DataAdapter.DicContentService.getDicContentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDicContentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDicContentResponseBody() {
        }
        
        public getDicContentResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDicContentChannel : EntFrm.DataAdapter.DicContentService.IDicContent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DicContentClient : System.ServiceModel.ClientBase<EntFrm.DataAdapter.DicContentService.IDicContent>, EntFrm.DataAdapter.DicContentService.IDicContent {
        
        public DicContentClient() {
        }
        
        public DicContentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DicContentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DicContentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DicContentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntFrm.DataAdapter.DicContentService.getDicContentByPageResponse EntFrm.DataAdapter.DicContentService.IDicContent.getDicContentByPage(EntFrm.DataAdapter.DicContentService.getDicContentByPage request) {
            return base.Channel.getDicContentByPage(request);
        }
        
        public string getDicContentByPage(string serviceID, string pageNum) {
            EntFrm.DataAdapter.DicContentService.getDicContentByPage inValue = new EntFrm.DataAdapter.DicContentService.getDicContentByPage();
            inValue.Body = new EntFrm.DataAdapter.DicContentService.getDicContentByPageBody();
            inValue.Body.serviceID = serviceID;
            inValue.Body.pageNum = pageNum;
            EntFrm.DataAdapter.DicContentService.getDicContentByPageResponse retVal = ((EntFrm.DataAdapter.DicContentService.IDicContent)(this)).getDicContentByPage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntFrm.DataAdapter.DicContentService.getDicContentByPageResponse> EntFrm.DataAdapter.DicContentService.IDicContent.getDicContentByPageAsync(EntFrm.DataAdapter.DicContentService.getDicContentByPage request) {
            return base.Channel.getDicContentByPageAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntFrm.DataAdapter.DicContentService.getDicContentByPageResponse> getDicContentByPageAsync(string serviceID, string pageNum) {
            EntFrm.DataAdapter.DicContentService.getDicContentByPage inValue = new EntFrm.DataAdapter.DicContentService.getDicContentByPage();
            inValue.Body = new EntFrm.DataAdapter.DicContentService.getDicContentByPageBody();
            inValue.Body.serviceID = serviceID;
            inValue.Body.pageNum = pageNum;
            return ((EntFrm.DataAdapter.DicContentService.IDicContent)(this)).getDicContentByPageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntFrm.DataAdapter.DicContentService.getDicContentResponse EntFrm.DataAdapter.DicContentService.IDicContent.getDicContent(EntFrm.DataAdapter.DicContentService.getDicContent request) {
            return base.Channel.getDicContent(request);
        }
        
        public string getDicContent(string serviceID, string fieldName, string fieldValue) {
            EntFrm.DataAdapter.DicContentService.getDicContent inValue = new EntFrm.DataAdapter.DicContentService.getDicContent();
            inValue.Body = new EntFrm.DataAdapter.DicContentService.getDicContentBody();
            inValue.Body.serviceID = serviceID;
            inValue.Body.fieldName = fieldName;
            inValue.Body.fieldValue = fieldValue;
            EntFrm.DataAdapter.DicContentService.getDicContentResponse retVal = ((EntFrm.DataAdapter.DicContentService.IDicContent)(this)).getDicContent(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntFrm.DataAdapter.DicContentService.getDicContentResponse> EntFrm.DataAdapter.DicContentService.IDicContent.getDicContentAsync(EntFrm.DataAdapter.DicContentService.getDicContent request) {
            return base.Channel.getDicContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntFrm.DataAdapter.DicContentService.getDicContentResponse> getDicContentAsync(string serviceID, string fieldName, string fieldValue) {
            EntFrm.DataAdapter.DicContentService.getDicContent inValue = new EntFrm.DataAdapter.DicContentService.getDicContent();
            inValue.Body = new EntFrm.DataAdapter.DicContentService.getDicContentBody();
            inValue.Body.serviceID = serviceID;
            inValue.Body.fieldName = fieldName;
            inValue.Body.fieldValue = fieldValue;
            return ((EntFrm.DataAdapter.DicContentService.IDicContent)(this)).getDicContentAsync(inValue);
        }
    }
}
